[2025-01-15T04:36:59.681+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-15T04:36:59.705+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomato_pipeline.eval_model manual__2025-01-15T04:34:24.950427+00:00 [queued]>
[2025-01-15T04:36:59.717+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomato_pipeline.eval_model manual__2025-01-15T04:34:24.950427+00:00 [queued]>
[2025-01-15T04:36:59.718+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-15T04:36:59.734+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): eval_model> on 2025-01-15 04:34:24.950427+00:00
[2025-01-15T04:36:59.742+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-15T04:36:59.744+0000] {standard_task_runner.py:72} INFO - Started process 148 to run task
[2025-01-15T04:36:59.745+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tomato_pipeline', 'eval_model', 'manual__2025-01-15T04:34:24.950427+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/craw_check_update.py', '--cfg-path', '/tmp/tmp_lz9rwmg']
[2025-01-15T04:36:59.746+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask eval_model
[2025-01-15T04:36:59.800+0000] {task_command.py:467} INFO - Running <TaskInstance: tomato_pipeline.eval_model manual__2025-01-15T04:34:24.950427+00:00 [running]> on host 03b22c562543
[2025-01-15T04:36:59.884+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomato_pipeline' AIRFLOW_CTX_TASK_ID='eval_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T04:34:24.950427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-15T04:34:24.950427+00:00'
[2025-01-15T04:36:59.886+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-15T04:36:59.886+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-15T04:36:59.887+0000] {logging_mixin.py:190} INFO - Current task name:eval_model state:running start_date:2025-01-15 04:36:59.705954+00:00
[2025-01-15T04:36:59.887+0000] {logging_mixin.py:190} INFO - Dag name:tomato_pipeline and current dag run status:running
[2025-01-15T04:36:59.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-15T04:36:59.888+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'
[2025-01-15T04:36:59.911+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-15T04:36:59.912+0000] {logging_mixin.py:190} INFO - Task start:2025-01-15 04:36:59.705954+00:00 end:2025-01-15 04:36:59.911075+00:00 duration:0.205121
[2025-01-15T04:36:59.913+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): eval_model> dag:<DAG: tomato_pipeline> dagrun:<DagRun tomato_pipeline @ 2025-01-15 04:34:24.950427+00:00: manual__2025-01-15T04:34:24.950427+00:00, state:running, queued_at: 2025-01-15 04:34:24.977678+00:00. externally triggered: True>
[2025-01-15T04:36:59.913+0000] {logging_mixin.py:190} INFO - Failure caused by eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'
[2025-01-15T04:36:59.914+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=tomato_pipeline, task_id=eval_model, run_id=manual__2025-01-15T04:34:24.950427+00:00, execution_date=20250115T043424, start_date=20250115T043659, end_date=20250115T043659
[2025-01-15T04:36:59.935+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-15T04:36:59.936+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task eval_model (eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'; 148)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'
[2025-01-15T04:37:00.004+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-15T04:37:00.027+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-15T04:37:00.030+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
