[2025-01-15T04:42:06.076+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-15T04:42:06.093+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomato_pipeline.eval_model scheduled__2025-01-15T03:00:00+00:00 [queued]>
[2025-01-15T04:42:06.102+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomato_pipeline.eval_model scheduled__2025-01-15T03:00:00+00:00 [queued]>
[2025-01-15T04:42:06.102+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-15T04:42:06.117+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): eval_model> on 2025-01-15 03:00:00+00:00
[2025-01-15T04:42:06.125+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-15T04:42:06.126+0000] {standard_task_runner.py:72} INFO - Started process 224 to run task
[2025-01-15T04:42:06.127+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tomato_pipeline', 'eval_model', 'scheduled__2025-01-15T03:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/craw_check_update.py', '--cfg-path', '/tmp/tmp8px1fw3s']
[2025-01-15T04:42:06.128+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask eval_model
[2025-01-15T04:42:06.176+0000] {task_command.py:467} INFO - Running <TaskInstance: tomato_pipeline.eval_model scheduled__2025-01-15T03:00:00+00:00 [running]> on host 03b22c562543
[2025-01-15T04:42:06.252+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomato_pipeline' AIRFLOW_CTX_TASK_ID='eval_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-15T03:00:00+00:00'
[2025-01-15T04:42:06.253+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-15T04:42:06.254+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-15T04:42:06.254+0000] {logging_mixin.py:190} INFO - Current task name:eval_model state:running start_date:2025-01-15 04:42:06.093694+00:00
[2025-01-15T04:42:06.255+0000] {logging_mixin.py:190} INFO - Dag name:tomato_pipeline and current dag run status:running
[2025-01-15T04:42:06.255+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-15T04:42:06.257+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'
[2025-01-15T04:42:06.266+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-15T04:42:06.266+0000] {logging_mixin.py:190} INFO - Task start:2025-01-15 04:42:06.093694+00:00 end:2025-01-15 04:42:06.265801+00:00 duration:0.172107
[2025-01-15T04:42:06.267+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): eval_model> dag:<DAG: tomato_pipeline> dagrun:<DagRun tomato_pipeline @ 2025-01-15 03:00:00+00:00: scheduled__2025-01-15T03:00:00+00:00, state:running, queued_at: 2025-01-15 04:34:25.204196+00:00. externally triggered: False>
[2025-01-15T04:42:06.267+0000] {logging_mixin.py:190} INFO - Failure caused by eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'
[2025-01-15T04:42:06.268+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tomato_pipeline, task_id=eval_model, run_id=scheduled__2025-01-15T03:00:00+00:00, execution_date=20250115T030000, start_date=20250115T044206, end_date=20250115T044206
[2025-01-15T04:42:06.280+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-15T04:42:06.280+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task eval_model (eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'; 224)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: eval_model() missing 3 required positional arguments: 'current_day', 'EXPERIMENT_DIR', and 'WEIGHT_DIR'
[2025-01-15T04:42:06.310+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-15T04:42:06.326+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-15T04:42:06.328+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
