[2025-01-14T03:33:07.322+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T03:33:07.344+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_and_update_model.check_and_train scheduled__2025-01-14T02:00:00+00:00 [queued]>
[2025-01-14T03:33:07.355+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_and_update_model.check_and_train scheduled__2025-01-14T02:00:00+00:00 [queued]>
[2025-01-14T03:33:07.356+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-14T03:33:07.377+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_and_train> on 2025-01-14 02:00:00+00:00
[2025-01-14T03:33:07.388+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T03:33:07.390+0000] {standard_task_runner.py:72} INFO - Started process 191 to run task
[2025-01-14T03:33:07.391+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_and_update_model', 'check_and_train', 'scheduled__2025-01-14T02:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/craw_check_update.py', '--cfg-path', '/tmp/tmpx8noaez5']
[2025-01-14T03:33:07.393+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask check_and_train
[2025-01-14T03:33:07.460+0000] {task_command.py:467} INFO - Running <TaskInstance: train_and_update_model.check_and_train scheduled__2025-01-14T02:00:00+00:00 [running]> on host 0d9f7ac256fb
[2025-01-14T03:33:07.581+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_and_update_model' AIRFLOW_CTX_TASK_ID='check_and_train' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T02:00:00+00:00'
[2025-01-14T03:33:07.583+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-14T03:33:07.584+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-14T03:33:07.585+0000] {logging_mixin.py:190} INFO - Current task name:check_and_train state:running start_date:2025-01-14 03:33:07.345683+00:00
[2025-01-14T03:33:07.585+0000] {logging_mixin.py:190} INFO - Dag name:train_and_update_model and current dag run status:running
[2025-01-14T03:33:07.586+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T03:33:07.587+0000] {craw_check_update.py:39} INFO - === Bắt đầu quá trình kiểm tra model ===
[2025-01-14T03:33:07.589+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/craw_check_update.py", line 135, in check_and_train
    eval_model()
  File "/opt/airflow/dags/craw_check_update.py", line 42, in eval_model
    current = datetime.strptime(CURRENT_DAY, format)
                                ^^^^^^^^^^^
NameError: name 'CURRENT_DAY' is not defined
[2025-01-14T03:33:07.615+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T03:33:07.616+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 03:33:07.345683+00:00 end:2025-01-14 03:33:07.614284+00:00 duration:0.268601
[2025-01-14T03:33:07.617+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): check_and_train> dag:<DAG: train_and_update_model> dagrun:<DagRun train_and_update_model @ 2025-01-14 02:00:00+00:00: scheduled__2025-01-14T02:00:00+00:00, state:running, queued_at: 2025-01-14 03:33:05.403977+00:00. externally triggered: False>
[2025-01-14T03:33:07.617+0000] {logging_mixin.py:190} INFO - Failure caused by name 'CURRENT_DAY' is not defined
[2025-01-14T03:33:07.618+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=train_and_update_model, task_id=check_and_train, run_id=scheduled__2025-01-14T02:00:00+00:00, execution_date=20250114T020000, start_date=20250114T033307, end_date=20250114T033307
[2025-01-14T03:33:07.639+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T03:33:07.641+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task check_and_train (name 'CURRENT_DAY' is not defined; 191)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/craw_check_update.py", line 135, in check_and_train
    eval_model()
  File "/opt/airflow/dags/craw_check_update.py", line 42, in eval_model
    current = datetime.strptime(CURRENT_DAY, format)
                                ^^^^^^^^^^^
NameError: name 'CURRENT_DAY' is not defined
[2025-01-14T03:33:07.695+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-14T03:33:07.721+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T03:33:07.723+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
